import type { BriefItem } from "../ai";

function formatDateTime(d: Date): string {
  return d.toLocaleString("en-US", {
    weekday: "short",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  });
}

function formatItemDate(iso: string): string {
  const d = new Date(iso);
  if (isNaN(d.getTime())) return iso;
  return d.toLocaleString("en-US", {
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  });
}

function renderItem(item: BriefItem): string {
  const lines: string[] = [];
  lines.push(`### ${item.title}`);
  lines.push(`*${formatItemDate(item.date)}*\n`);
  lines.push(item.body + "\n");
  lines.push(`> *${item.why}*\n`);
  lines.push(
    `Sources: ${item.sources.map((s) => `[${s.name}](${s.url})`).join(", ")}\n`
  );
  return lines.join("\n");
}

export function renderMarkdown(items: BriefItem[]): string {
  const now = new Date();

  // Derive actual source time range from item dates
  const itemDates = items
    .map((i) => new Date(i.date))
    .filter((d) => !isNaN(d.getTime()))
    .sort((a, b) => a.getTime() - b.getTime());

  const oldest = itemDates.length > 0 ? itemDates[0] : now;
  const newest = itemDates.length > 0 ? itemDates[itemDates.length - 1] : now;

  const lines: string[] = [];
  lines.push(`# PulseBrief`);
  lines.push(`*Generated ${formatDateTime(now)}*`);
  lines.push(`*Sources from ${formatDateTime(oldest)} → ${formatDateTime(newest)}*\n`);

  if (items.length === 0) {
    lines.push("Nothing significant in this window.");
    return lines.join("\n");
  }

  const signalItems = items.filter((i) => i.section === "signal");
  const industryItems = items.filter((i) => i.section === "industry");

  if (signalItems.length > 0) {
    lines.push("## Signal\n");
    signalItems.forEach((item) => lines.push(renderItem(item)));
  }

  if (industryItems.length > 0) {
    lines.push("## Industry\n");
    industryItems.forEach((item) => lines.push(renderItem(item)));
  }

  lines.push("---");
  lines.push("*Generated by PulseBrief*");

  return lines.join("\n");
}

export function renderHtml(markdown: string): string {
  return markdown
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/^> (.+)$/gm, "<blockquote>$1</blockquote>")
    .replace(/\[(.+?)\]\((.+?)\)/g, '<a href="$2">$1</a>')
    .replace(/^---$/gm, "<hr>")
    .replace(/\n\n/g, "</p><p>")
    .replace(/\n/g, "<br>")
    .replace(/^/, "<html><body style='font-family: system-ui, sans-serif; max-width: 640px; margin: 0 auto; padding: 20px;'><p>")
    .replace(/$/, "</p></body></html>");
}
