export async function deliverByResend(
  html: string,
  subject: string,
  from: string,
  to: string[]
): Promise<void> {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    throw new Error("RESEND_API_KEY environment variable is not set");
  }

  // Send individually so recipients don't see each other
  for (const recipient of to) {
    const response = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from,
        to: [recipient],
        subject,
        html: wrapEmailHtml(html),
      }),
    });

    if (!response.ok) {
      const body = await response.text();
      console.error(`[deliver] Resend error for ${recipient}: ${body}`);
    } else {
      console.log(`[deliver] Email sent to ${recipient}`);
    }
  }
}

function wrapEmailHtml(bodyHtml: string): string {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--[if mso]><noscript><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml></noscript><![endif]-->
</head>
<body style="margin: 0; padding: 0; background-color: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;">
  <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background-color: #f5f5f5;">
    <tr>
      <td align="center" style="padding: 24px 16px;">
        <table role="presentation" width="640" cellspacing="0" cellpadding="0" style="background-color: #ffffff; border-radius: 8px; overflow: hidden; max-width: 640px; width: 100%;">
          <tr>
            <td style="padding: 32px 32px 24px; border-bottom: 2px solid #1a1a1a;">
              ${bodyHtml
                .replace(/<h1>(.*?)<\/h1>/g, '<h1 style="margin: 0 0 8px; font-size: 24px; font-weight: 700; color: #1a1a1a;">$1</h1>')
                .replace(/<h2>(.*?)<\/h2>/g, '</td></tr><tr><td style="padding: 24px 32px 8px; border-top: 1px solid #eee;"><h2 style="margin: 0 0 16px; font-size: 14px; font-weight: 600; color: #888; text-transform: uppercase; letter-spacing: 0.5px;">$1</h2>')
                .replace(/<h3>(.*?)<\/h3>/g, '<h3 style="margin: 20px 0 4px; font-size: 16px; font-weight: 600; color: #1a1a1a; line-height: 1.3;">$1</h3>')
                .replace(/<em>(.*?)<\/em>/g, '<span style="color: #666; font-style: italic;">$1</span>')
                .replace(/<blockquote>(.*?)<\/blockquote>/g, '<div style="border-left: 3px solid #ddd; padding-left: 12px; margin: 8px 0 12px; color: #555; font-size: 14px;">$1</div>')
                .replace(/<hr>/g, '')
                .replace(/<a /g, '<a style="color: #0066cc; text-decoration: none;" ')
                .replace(/<p>/g, '<p style="margin: 0 0 12px; font-size: 15px; line-height: 1.6; color: #333;">')
              }
            </td>
          </tr>
          <tr>
            <td style="padding: 16px 32px; background-color: #fafafa; text-align: center; font-size: 12px; color: #999;">
              Generated by PulseBrief
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}
